version: '3.3'
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: web
        ports:
            - "8181:8181"
        volumes :
            - ".:/project"
        networks:
            - myNetwork
        depends_on:
            - db
            - redis

    db:
        image: mysql:5.7
        container_name: db
        ports:
            - 33061:3306
        volumes:
            - dbdata:/var/lib/mysql/
        environment:
            - MYSQL_ROOT_PASSWORD=secret_root_password
            - MYSQL_DATABASE=your_database
            - MYSQL_USER=your_user
            - MYSQL_PASSWORD=your_password
        networks:
            - myNetwork

    redis:
        image: redis:7.0.0-alpine
        container_name: redis
        networks:
            - myNetwork

    redis-commander:
        container_name: redis-commander
        image: rediscommander/redis-commander:latest
        restart: always
        environment:
            - REDIS_HOSTS=local:redis:6379
        ports:
            - "8182:8081"
        networks:
            - myNetwork
        depends_on:
            - redis

volumes:
    dbdata:
        driver: local

networks:
    myNetwork:
        driver: bridge
